version: '3'

services:
  # BACKEND: Node.js server
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    # Konteiner näeb välja nagu kohalik server pordil 3000

  # FRONTEND: React app serveeritud NGINX-iga
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    # Valmis build serveeritakse port 8080 kaudu
