name: Deploy to DigitalOcean (Container Registry)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Logi sisse DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push backend
        run: |
          docker build -t registry.digitalocean.com/todo-registry/todo-backend:latest ./backend
          docker push registry.digitalocean.com/todo-registry/todo-backend:latest
